/**
 * Root application layout for SCTR Insurance Document Generator.
 *
 * This server component defines the shared HTML structure, global fonts,
 * application metadata, dark theme, and base styling used by every route.
 *
 * Responsibilities:
 * - Load Geist Sans and Geist Mono font families through Next.js.
 * - Expose font variables for use throughout the application's CSS.
 * - Define default metadata for browser tabs and search previews.
 * - Apply global layout, theme, and typography classes.
 * - Render route-specific content through the `children` prop.
 */

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

/**
 * Primary sans-serif font used for general interface text.
 *
 * Next.js downloads and optimizes font at build time. The generated CSS
 * variable can be referenced as `--font-geist-sans` throughout the application.
 */
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

/**
 * Monospaced font available for technical or fixed-width content.
 *
 * Generated CSS variable can be referenced as `--font-geist-mono`.
 */
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/**
 * Default metadata applied to the application.
 *
 * Route-level metadata able to override these values when a page requires a more
 * specific title or description.
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Defines shared document shell for every route in the application.
 *
 * @param children - Page or nested-layout content rendered inside the body.
 * @returns The root HTML structure used by the Next.js App Router.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-dvh overflow-x-hidden bg-zinc-950 text-zinc-100 antialiased`}
      >
        {children}
      </body>
    </html>
  );
}